# Generated by Django 4.2 on 2023-06-16 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjoin', models.DateField()),
                ('sname', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=30)),
                ('smobile', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$')])),
                ('creat_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
