# Generated by Django 4.2 on 2023-06-16 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_regno', models.IntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_mobile', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$')])),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
